name: Release Preview

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 打包项目为 zip
        run: zip -r project.zip . -x ".git/*"

      - name: 生成版本号
        id: vars
        run: echo "RELEASE_TAG=preview-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: 创建预览版 Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: 预览版 ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: true

      - name: 上传 zip 到 Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./project.zip
          asset_name: project.zip
          asset_content_type: application/zip
